// <auto-generated />
namespace endmystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class KeywordandBooksKeywordsTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KeywordandBooksKeywordsTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201308221746060_Keyword and BooksKeywords Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
